server {
    listen 8081;
    server_name ga-client-server;
    server_tokens off;
    root /usr/share/nginx/html;
    port_in_redirect off; # Disable port in redirects for use behind a reverse proxy; set to 'on' for direct access (e.g. local development)

    location /ga/demo-map/ {
        index index.html;
        try_files $uri /ga/demo-map/index.html;
    }

    location = /ga/demo-map {
        return 301 /ga/demo-map/;
    }
}